server:
  port: 8080

spring:
  application:
    name: auth-service

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  secret-key: ${COOLSMS_API_SECRET}
  sender-phone-number: ${COOLSMS_PHONE_NUMBER}
  domain: https://api.coolsms.co.kr

JWT:
  secret-key: ${JWT_SECRET}
  token:
    access-expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
    refresh-expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}

feign:
  client:
    member-service:
      url: ${MEMBER_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /auth-service/v3/api-docs/swagger-config
    url: /auth-service/v3/api-docs