name: CI

on:
  push:
    branches:
      - develop


env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: cabbage/{}-service   ### 각자 서비스명에 수정 필요
  SERVICE_NAME: search-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  ### 레포지토리에 액세스키 시크릿 추가
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} ### 레포지토리에 비밀키 시크릿 추가
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          ./gradlew bootJar
          docker build -t ${{ env.ECR_REPOSITORY }}:latest -f Dockerfile .

      - name: Tag & Push to ECR
        run: |
          REPO_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_REPOSITORY }} --region ${{ env.AWS_REGION }} --query "repositories[0].repositoryUri" --output text)
          docker tag ${{ env.ECR_REPOSITORY }}:latest $REPO_URI:latest
          docker push $REPO_URI:latest

      - name: Get image digest
        id: digest
        run: |
          IMAGE_DIGEST=$(aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --image-ids imageTag=latest --query 'imageDetails[0].imageDigest' --output text)
          echo "Image digest: $IMAGE_DIGEST"
          echo "